### PR TITLE
Add draft interface for accessing beam models

### PR DESCRIPTION
**Pull request by bmerry**

### CODE REVIEW

**Comment by bmerry** [comment]
@mattieudv could you take a look at this and see how it matches up to how your beam models actually work? For example:
- Are the sign conventions the same as yours? If not, I'd certainly consider changing them so that we don't need to sprinkle sign changes all over the code.
- Are there parameters other than antenna, frequency and elevation affect the models (within a single observation - I know there are also changes over time as receivers are swapped or panels adjusted, and it will vary per band)?
- Do you think it would be more appropriate to have frequency come out as another dimension from the sampling, rather than first picking a frequency and then sampling a beam model at that frequency?

**Comment by bmerry** [comment]
@mauch you might be interested as well. My theory is that eventually this could migrate into katdal (or possibly a separate package used by katdal) and katdal would provide beam models for each observation that could be shared between katsdpcontim and katsdpimager (and katsdpcal would probably need to use them eventually too for predict for complex models).

**Comment by mattieudv** [comment]
I use the 'inverse sine' projection where the reference and sampled coordinates are swapped to convert from AZEL to l,m. So these l,m coordinates are well defined. When the antenna points up above the target a measurement of the bottom part of the beam is made. So too left and right is swapped. Offhand my guess is it is the other way around from what you described.

MeerKAT is designed (according to Adriaan) to use only a single array average beam for all antennas, for all observation conditions, and that should be 'good enough'. For SKA they want to improve on that. It is unclear at this point, if in reality one do need per antenna results, or per elevation results in practise. It is best to atleast make the code compatible for this expansion.

Your basic core implementation should be 3 dimensional:
a) l,m direction cosine coordinates and I recommend you use l and m as the variables to describe these
b) frequency

I can either supply you beam values on a grid beam(f,m,l) [1024x128x128 or bigger] that you then need to interpolate however you like, or a much more compact/advanced model of fixed size in aperture-lag space [256x32x32 or smaller] that you can seamlessly evaluate to any arbitrary gridding in all dimensions f,m,l. Perhaps that is a bit too advanced however it would greatly simplify your interpolation issue. It is exact rather than approximate (interpolation only use neighbouring values). It might even be less expensive to compute. So for all these reasons it might be worth considering implementing this straight off the bat. There is great scope for optimising it because the occupancy in this lag space is limited. A transform like this would be the most valuable thing to do and would be a vital component towards sharing beams to other interested parties.

If you implement something like above, the remaining work on other dimensions is fairly trivial.

I mentioned that there is a significant elevation dependence on the beam models. For the moment one can ignore it. In the future I may opt to break this up the elevation dependence into separate equivalent collimation errors instead, so I would not pen down 'elevation' forever. In the future I may also specify other antennas in terms of collimation errors in this way. The important part is to have the option to do a combination of components before transform/interpolation is done.

Anything more than the core 3 dimensions can be dealt with in terms of bookkeeping for now (eg which antenna with which receiver), or else as described in the above paragraph.

**Comment by mattieudv** [comment]
I might not have addressed all your questions, feel free to ask for clarifications. Some points I missed: 
- Each band has independent results. Where frequencies overlap their shapes differ.
- Within a single observation elevation is the main effect causing change to a beam shape. Sun angle also has a significant effect but we do not need to get the system to optimal performance during daytime (one day maybe). Temperature has a small effect and wind speed and direction too but these are significantly less important compared to elevation. You need to allow for a cubic polynomial combination of 4 patterns to be able to interpolate over elevation. It is easy to do this. But perhaps try to keep this general enough that this could become more than one dimensional at a later stage. Elevation could in the short term be specified as a 1d cubic, but in the future I may want to specify various collimation error components (eg how the beam changes if we move the feed around). So keep the concept fairly general. This is not so important at this stage.
-I believe it is best to transform from aperturelag(z,y,x)->beam(f,m,l) exactly where you need it but it certainly is more conventional to pick a frequency and then sample the beam at that frequency. Currently I do this in two steps, and it may be better to do it like this: first transform the lag dimension to required frequency channels, then from there transform aperture to beam plane rather than a true 3d transform in one step. Not sure a 3d version might be faster than 1+2d if one take advantage of low occupancy (say cells with small values can be ignored). I think the best reason for giving you aperture-lag instead of a beam is because the file size is much smaller and an aperture representation is more complete and native to what my holography code produces (even at 128x128 resolution it is not really a good representation of the beam that can be represented perfectly by a 32x32 aperture). I can also give you the code to transform aperture->beam and then one can maybe at a later stage optimise it. It just feels clumsy to store beams instead of apertures as files. The gridding and extent of beams is a bit arbitrary and its storage is wasteful.

**Comment by bmerry** [comment]
I've made some updates based on our discussions. There's also about 1/4 of an implementation for the simplest possible implementation.

**Comment by bmerry** [comment]
Closing in favour of #32.

**Pull request closed without merging**
