### PR TITLE
SPR1-2766: Update lupa to docker base version

### PR DESCRIPTION
**Pull request by ludwigschwardt**
This is precipitated by fakeredis 2.10.0 in docker base.

### CODE REVIEW

**Comment by bmerry** [comment]
I'm curious why lupa is even listed in requirements.txt. If you take it out, won't the version in dockerbase get used?

**Comment by ludwigschwardt** [comment]
It's in `test-requirements.txt`, which is why I missed it originally. It enters via `fakeredis`, which is used in the tests of both katsdptelstate and katsdpimager.

**Comment by bmerry** [comment]
> It's in `test-requirements.txt`, which is why I missed it originally. It enters via `fakeredis`, which is used in the tests of both katsdptelstate and katsdpimager.

Ah, I see docker-base doesn't pin a version for lupa. But docker-base does pin fakeredis, so I think it would make sense for it to pin lupa as well since we're unlikely to use fakeredis anywhere without lupa.

**Comment by ludwigschwardt** [comment]
Good point! One might also argue that only katsdptelstate and katsdpimager need fakeredis in their tests, so we could instead move fakeredis out of docker base...

**Comment by ludwigschwardt** [comment]
On a side note, I see that katsdpimager is still using nose :-)

**Comment by ludwigschwardt** [comment]
Rather adding lupa to docker base...

**Review by bmerry — APPROVED** [review]

**Pull request merged**
